### ISSUE TITLE
HTML Component Style Bug

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#1]
I am having problems with the code tags in Open edX studio in the HTML editor. Below is the code of my HTML segment

``` html
<h2>sample code</h2>
<p>
  <code>
    <span style="color: #000080;" color="#000080">ClassMethod </span>
    <span style="color:#000;" color="#000000">%OnGetJSONContent</span>
    <br />
  </code>
</p>
```

The Visual editor displays the component as follows:

![image02](https://cloud.githubusercontent.com/assets/417109/7947684/8cb9154a-0933-11e5-90d4-87c2b8d7a7fc.png)

The student view in edX displays it as follows:

![image00](https://cloud.githubusercontent.com/assets/417109/7947704/a3ce1b0e-0933-11e5-8ad1-1ca2d56e3f4d.png)

The monospace font is not displaying as expected. The link to display the student view is https://staging-lms.learning.intersystems.com/courses/InterSystems/ISC1017/2015_1/courseware/169d0a98a2284b6691a6b51702a371ac/ce000b1a3c334ad8a1f050ea1d08e5c6/4

The whole issue was to have the color within the code tags so that it displays in fixed width. The view of the component in Studio has the text formatted properly with color. The student view the edX course somehow doesn't display the fixed width. That is why I included the code snippet below so it could be tested out. I have no problems with the code tags creating fixed width when enclosed text has no color attributes.

(from: stuart.peters@intersystems.com)

**Comment by cewing** [comment]
@natea could you review this and ensure that the scope of action is clear for @bryanlandia

**Comment by bryanlandia** [comment]
Fixed in https://github.com/ISCLC/edx-theme/commit/be6cdf313d37fbfcb22cd2e8962cb149b9e40388

**Comment by bryanlandia** [comment]
@natea - Assigning to you to confirm before closing once you have a duplicated setup... not sure how you are planning to roll out our changes to staging.   Should be simple to test on your staging once you get it set up with named-release/birch edx-platform and our birch branch of ISCLC/edx-theme.

**Comment by natea** [comment]
@bryanlandia could you please document all the steps, in order to get an environment set up such that I can test and review these issues?

**Comment by bryanlandia** [comment]
@natea (also @cewing @cguardia @skleinfeldt) - I've written up the steps I've used to create my Vagrant vm based on named-release/birch, using our isc/birch edx-platform, and our birch branch of isc.  It's more manual than what was set up before pre-birch (but I never got to work) at /Jazkarta/ISC/ but it worked for me.  Let me know if you have any issues

https://github.com/jazkarta/edx-platform-for-isc/wiki#setting-up-an-isc-testing-environment

**Comment by bryanlandia** [comment]
This is deployed on staging but is not working. The span tag CSS is overrideing the code tag CSS still.  Will revisit tomorrow...

**Comment by bryanlandia** [comment]
Closing—working on staging.
