### ISSUE TITLE
ISC Customizations: Allow arbitrary course intro video urls and embed codes

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#15]
The existing edx implementation only allows for adding a course intro video by YouTube id.  ISC has customized that to allow for an arbitrary video url as well as a hand-composed embed code.  The changes are in these two changesets:
- https://github.com/jazkarta/edx-platform/commit/8a5b5953e2a99297ba0c87afb7e802eecd93b109
- https://github.com/jazkarta/edx-platform/commit/d6ab5cd1c10d711901c3331db048371960ca2dd4

It is not clear at the time of creating this issue if the second use case (providing an arbitrary embed code) is actually required.

**Comment by cewing** [comment]
@natea could you please follow up on the open question of whether the ISC people require arbitrary embed codes in addition to arbitrary video urls?  The document does not make that clear.

**Comment by natea** [comment]
@cewing I asked Jenny in the gdoc "Intersystems enhancements to Open edX" if they need both video embed codes or just video urls.

**Comment by cewing** [comment]
@natea great.  Can you transcribe her response, when it arrives?

**Comment by natea** [comment]
yes, it will likely come as a comment on that gdoc, but i can paste it into
this issue so we have it documented all in one place.

On Wed, Jun 17, 2015 at 2:49 PM, Cris Ewing notifications@github.com
wrote:

> @natea https://github.com/natea great. Can you transcribe her response,
> when it arrives?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazkarta/edx-platform-for-isc/issues/15#issuecomment-112911994
> .

## 

nate@appsembler.com
+1 (617) 517-4953
http://twitter.com/natea | http://linkedin.com/in/natea

**Comment by bryanlandia** [comment]
PR https://github.com/jazkarta/edx-platform-for-isc/pull/18
handles both changesets.  There wasn't yet a definitive answer about the second changeset from Jenny, but having looked at the code, there wasn't a significant difference in amount of work between implementing one or both and I couldn't see a real downside to allowing embed code, too.

**Comment by bryanlandia** [comment]
@natea - ready for review

**Comment by bryanlandia** [comment]
Closing after review on staging server.
