### ISSUE TITLE
ISC Customizations: Allow self-completed courses

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#16]
The work allowing this was completed in the following changesets:
- https://github.com/jazkarta/edx-platform/commit/1592b27554d836280d2e776f0ba3326d0d30c30b
- https://github.com/jazkarta/edx-platform/commit/6ea02a1932db6fbabc8d2dca264c0cf569d2561a
- https://github.com/jazkarta/edx-platform/commit/10dced4bf62beb237645a12822c3735aef43effb

There are a few open questions to the original author, @cguardia, on these changesets.  They should be addressed before this work is undertaken.

In addition, it is not clear to me how this feature differs from the availability of On-Demand certificates for self-paced courses [available in core edx](http://edx-guide-for-students.readthedocs.org/en/latest/SFD_certificates.html#on-demand-certificates).  Could we get a read on that please, @natea?

**Comment by cewing** [comment]
We need to evaluate whether the ability to have on-demand certificates is available in the birch named release.  @cguardia, might you take this on?

**Comment by natea** [comment]
@cguardia what did you find out about the Birch capabilities versus what you built?

**Comment by cguardia** [comment]
Birch does not have the request certificate capability. However, I think it would be better for us to back port the feature, rather than using the earlier code I wrote.

**Comment by natea** [comment]
@cguardia are you saying that Birch doesn't have it but the current master branch has it? We could also just wait until Cypress comes out which will surely have it, if they don't need this feature until then.

**Comment by cguardia** [comment]
Yeah, Birch doesn't have it but it's on master.

**Comment by cguardia** [comment]
To be clear, what's on master does more or less what I did, but is better integrated, so I would say if we can wait, let's wait, if not let's back port it.

**Comment by skleinfeldt** [comment]
@cguardia please go ahead with the backporting idea. @natea isn't available today, and @cewing and I think it's the way to go. Just make sure it will be easy to remove when they upgrade to the next release.

**Comment by cguardia** [comment]
The work I have done on this is here:

https://github.com/jazkarta/edx-platform-for-isc/tree/backport-auto-certification

There are still some test failures. @bryanlandia, @natea will you take care of those or do you want me to track them down?

**Comment by bryanlandia** [comment]
There are a lot of broken tests in `named-release/birch` "out of the box", at least using `--settings-test` (don't know why we wouldn't use those settings for `manage.py lms test`...) making it very difficult to determine if new changes are causing any problems.

I can see that a whole slew of tests started breaking between edx-platform commits:
435b75b1940b7af7eaba7163a37bda7d67cd50b6 (working)
and
b353ed2ea2c92ae028949a563194d28cf95c1442 (broken).

The tests are broken in `named-release/birch`, from which isc-birch-patches and (I believe) all of our feature branches were created, but working in `master`.

That said, it does appear there are some relevant _errors_ when running the tests on the `certificates` django app... continuing investigation.

**Comment by bryanlandia** [comment]
OK, I've checked all of the relevant tests in the certificates and courseware django apps and they all look good to me (had to fix a couple of problems with my vm and delete some pyc files first!)  It's ready to go.

**Comment by bryanlandia** [comment]
Merged https://github.com/jazkarta/edx-platform-for-isc/pull/21 to isc-birch-patches
@natea... please review

**Comment by bryanlandia** [comment]
@natea - I've been reviewing this Issue again and given my recent conversation with Jennifer,  I'm not sure that this backporting is providing the feature set they want.  I'm digging through the difference between the core edX auto certification and what Carlos had previously implemented.

**Comment by natea** [comment]
@bryanlandia if it's not doing what they expect, should we take the old feature that Jazkarta developed and move it forward to Birch, rather than using the new feature that edX provides?

**Comment by bryanlandia** [comment]
@natea - I'm sorting through the differences and comparing with the conversation in https://secure.helpscout.net/conversation/111514176/503/ . Will get a plan together

**Comment by bryanlandia** [comment]
Here are the differences I see between the three changesets implemented by @cguardia and what is provided by core edX's auto-certification:

cguardia:
- certificates are not queued to xqueue for generation but start with a 'downloadable' status
- progress tab for course will display a complete course button if student has passed the success cutoff value for the course
- complete course button that submits to new `request_grade` view
- if certificate is already 'ready' progress tab displays a 'course completed' method instead of a button
- eliminates dashboard message 'Final course details are being wrapped up at this time.'
- eliminates certificate download button on the dashboard page (ISC doesn't use certificates)
- Adds complete course button to dashboard course listings when student has passed success cutoff

core edX in next comment

**Comment by bryanlandia** [comment]
core edX (post-Birch, backported):
- relies on the xqueue to generate certificates
- allow certificate generation configuration per course
- adds messages (cert is ready) 'your certificate is available' and 'download' or, (cert is not ready but is in the queue) 'we're working on it'; or, 'congratulations you qualified for a certificate' and 'generate certificate' button to the progress page (if student has achieved qualifying score)
- no changes to certificate display on dashboard page

**Comment by bryanlandia** [comment]
I recommend reverting the backporting/merging  of the post-Birch auto-generated certificate code and going back to Carlos' previous code.  ISC doesn't use certificates, so all of the language around auto-generated certificates needs to be changed and the functionality for configuring/enabling auto-generated certificates, generating Example Certificates before allowing access to the configuration options in the UI, additional reliance on xqueue is problematic in their case.  As much as it's also problematic to maintain a divergent set of features for ISC, I think it's the better choice for now.  There are some additional small refinements requested by Jennifer that will make more sense to do based on the previous code from Carlos' modifications to the Aspen codebase.

**Comment by natea** [comment]
@bryanlandia does this pose any problems if ISC decides later that they want to start using certificates?

**Comment by bryanlandia** [comment]
yes, the code would need to be changed if they start using certificates.  the language won't make sense and the xqueue for cert generation would need to be re-enabled.

**Comment by natea** [comment]
Could we have both course complete button and cert generation or is it a
one or the other situation?

On Thursday, August 13, 2015, Bryan Wilson notifications@github.com wrote:

> yes, the code would need to be changed if they start using certificates.
> the language won't make sense and the xqueue for cert generation would need
> to be re-enabled.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazkarta/edx-platform-for-isc/issues/16#issuecomment-130730927
> .

## 

Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by bryanlandia** [comment]
I'm looking into it.  With Carlos' older code, the complete course button function uses some of the state machinery of the certificates API, but just sets the certificate state to `downloadable` immediately, and the code that updates the xqueue with the new cert to generate is commented out.  That disables the generation/updating queue/callback functionality for certificates.  It's an expedient but not very flexible approach.  We'd need to add some additional configuration to allow true cert generation and also bypass real certs and still provide course completion and grade notification.  I'm going to look at this a bit more, but ISC doesn't use certificates at this point, and we want to get this done for the Birch upgrade and rollout of Learning Paths.  There have been 65 commits in `lms/djangoapps/certificates` since named-release/birch up til today's Cypress release, so I'd be inclined to see if we will move ISC to Cypress by the time ISC wants to use certs.  So, at this point, I'm inclined to go with it as-is and add the additional flexibility at a later date if needed.

**Comment by natea** [comment]
Sounds good. Let's go with your suggestion, and revisit the certs question
with the Cypress upgrade.

On Thu, Aug 13, 2015 at 1:17 PM, Bryan Wilson notifications@github.com
wrote:

> I'm looking into it. With Carlos' older code, the complete course button
> function uses some of the state machinery of the certificates API, but just
> sets the certificate state to downloadable immediately, and the code that
> updates the xqueue with the new cert to generate is commented out. That
> disables the generation/updating queue/callback functionality for
> certificates. It's an expedient but not very flexible approach. We'd need
> to add some additional configuration to allow true cert generation and also
> bypass real certs and still provide course completion and grade
> notification. I'm going to look at this a bit more, but given that ISC
> doesn't use certificates at this point, and we want to get this done for
> the Birch upgrade and rollout of Learning Paths. There have been 65 commits
> in lms/djangoapps/certificates since named-release/birch up til today's
> Cypress release, so I'd be inclined to see if we will move ISC to Cypress
> by the time ISC wants to use certs. So, at this point, I'm inclined to go
> with it as-is and add the additional flexibility at a later date if needed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazkarta/edx-platform-for-isc/issues/16#issuecomment-130766305
> .

## 

Website: http://www.appsembler.com
Blog: http://www.appsembler.com/blog
Twitter: http://twitter.com/natea
LinkedIn: http://linkedin.com/in/natea
Phone: +1 (617) 702-4331

**Comment by bryanlandia** [comment]
We reverted the post-Birch core certificate merge and went with the older code, with some modifications.  Closing after review on staging server.
