### ISSUE TITLE
XBlock for SWF Simulations

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#2]
How easy is it to add a new component type with some pre-defined text? I've been copy and pasting HTML/javascript from previous courses to add a simulation to a page. However, I think it would be great to have it as an option when we add a New Component so we don't have to think about it. It's not top priority but if it's quick, I think it could save us a lot of time and headaches.

In case it matters, the text I'm copying/would should show up is:

``` html
<h2>Simulation</h2>
<p>Replace ISCxxxx with your course number, the simulation name and the static image name to implement a simulation. </p>
<script>// <![CDATA[
// Popup window code
function newPopup(url) {
popupWindow = window.open(
url,'popUpWindow','left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
}
// ]]></script>
<p><a onclick="newPopup("https://staging-lms.learning.intersystems.com/c4x/InterSystems/ISCxxxx/asset/set.swf")"><img src="/static/setVidImage2.png" type="saveimage" target="[object Object]" width="650" /></a></p>
```

Having it as a popup is a requirement. We also have other simulations that are embedded on the page but the code we've used is something like this:

``` html
<center><object data="/static/IconSim.swf" type="application/x-shockwave-flash" height="200" width="45%">
</object></center>
```

(from Jennifer.Ames@intersystems.com)

**Comment by cewing** [comment]
From @natea:

It looks like you're launching a SWF file? Perhaps we could explore using this XBlock which accepts a SWF file as input, and can then display it embedded on the page or can be optionally downloaded. I'm
not sure if it has a pop-up option, but if not, that's something we could add w/o too much work. 

```
https://github.com/MarCnu/flashXBlock
```

If this flashXBlock doesn't work for you, we could look into building a custom XBlock that behaves the same way your current HTML/Javascript paste method works, but you wouldn't have to copy/paste since it would use the same HTML/Javscript code for all the SWF files, but we would parameterize the file to be loaded.

That also gives you the option of updating the HTML/Javascript code only once if you want to change the way SWF files are displayed, and that change would be reflected for each individual SWF embed used throughout all the courses.

**Comment by cewing** [comment]
@natea, the scope of work for this ticket is unclear.  Please clarify exactly which we are to do here from among the options discussed and offered.

**Comment by natea** [comment]
@cguardia @cewing the purpose of this ticket is to investigate whether the flashXBlock will meet their needs. If it doesn't have a pop-up option, we would add that to the JS, so that rather than embedding the Flash file in the edX course page, it would be a link when clicked would show the Flash file in a new window (this is because many of the ISC simulations take up a lot of window space, and won't fit within the edX course page area).

This popup should probably be an optional parameter, so the original behavior is still available, if the user wants to embed the file directly in the edX course page.

**Comment by cguardia** [comment]
The XBlock does not have a popup option, but I have added one locally. Should we fork?

I installed the XBlock manually, but I'm not sure how to add one to the configuration.

**Comment by natea** [comment]
I'd say fork it and submit a PR to the author. Were you able to add it to
the configuration from the pointers I gave you during our standup call
today?

On Thu, Jun 11, 2015 at 3:04 PM, Carlos de la Guardia <
notifications@github.com> wrote:

> The XBlock does not have a popup option, but I have added one locally.
> Should we fork?
> 
> I installed the XBlock manually, but I'm not sure how to add one to the
> configuration.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazkarta/edx-platform-for-isc/issues/2#issuecomment-111240794
> .

## 

nate@appsembler.com
+1 (617) 517-4953
http://twitter.com/natea | http://linkedin.com/in/natea

**Comment by natea** [comment]
@cguardia any feedback from the author on the PR?

**Comment by cguardia** [comment]
No feedback yet. We might need to use my fork if nothing comes from it.

**Comment by cguardia** [comment]
Still no feedback. Here's my fork, just in case:

https://github.com/cguardia/flashXBlock

**Comment by skleinfeldt** [comment]
We're going to assume we're going to use the fork.

**Comment by bryanlandia** [comment]
Deployed and working on staging.  Closing.
