### ISSUE TITLE
Revert course handouts removal

### ISSUE THREAD

**Issue by natea** [jazkarta/edx-platform-for-isc#20]
Course handouts

There was as change to made to handle “Course Handouts” that prevents us from editing that information and having it display. This is information from TJ:

Just following up on this old ticket.

I looked into the code and it seems like the Handouts section isn't appearing on the Course Info tab because it was deliberately removed by Jazkarta (the date of the code change was 9/30/2014). That was way before I was involved with the project, so i'm not sure if it was disabled because somebody requested that it be removed, or if it was causing some other functionality to break. I can get in touch with the original author and see if he knows, or I can try enabling that section of the page and see if anything breaks.

Let me know how you'd like me to proceed.

-TJ

Janine says: "We have handouts for our courses, so would like this feature. I don't know why it was disabled. We never got this feature to work. We'd like to make sure it works for future."

Nate replied: "It was removed because at the time, the handouts section was taking up space on the page, and I think Faezeh wanted to use that space to embed a simulation video. We can revert this change, if it's more important for you to have the handouts feature than it is to have the real estate for embedding the simulation videos. (that is why handouts were originally requested to be removed by Faezeh). My suggestion would be to have all simulations load in a popup window, rather than be embedded in the page. This will avoid the limited real estate issue."

**Comment by tkeemon** [comment]
This is the commit I was referencing in the email:
https://github.com/ISCLC/edx-theme/commit/0ed9b8443ce927c0a5d44ff023f3e95d11a81e7d

**Comment by bryanlandia** [comment]
Might only have enough time left in the Jazkarta contract to just put back the handouts section, but will look at having videos appear in a popup.

**Comment by bryanlandia** [comment]
Deletion of theme template override made directly to ISCLC/edx-theme birch branch.
@natea .. Please review

**Comment by bryanlandia** [comment]
Confirmed working on isc_appsembler dev site
