### ISSUE TITLE
ISC Customizations: Make export tarball name easier to identify

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#5]
Preserve the change made in these two commits (first only for context, second represents final state):
- https://github.com/jazkarta/edx-platform/commit/a7ea7a206b1e93b865782fb6328f0d17e2150efa#diff-9c9857a74d1833510d4b8bffb4c02794
- https://github.com/jazkarta/edx-platform/commit/50d31349d95b9e7f9d92db2c1404602595dd2591#diff-9c9857a74d1833510d4b8bffb4c02794

The target for the change is in a [different function](https://github.com/jazkarta/edx-platform-for-isc/blob/master/cms/djangoapps/contentstore/views/import_export.py#L361) in the Birch release

**Comment by cewing** [comment]
@natea: there is a second commit referenced in the document explaining this change, but it appears to be unrelated to this change (the same commit hash appears again in a later set of changes related to the HTML component).  Could you please confirm that [this commit](https://github.com/jazkarta/edx-platform/commit/489f525ed2f420be8790e051365e1c7ef47e3fb0) has nothing to do with the exporting of courses?

**Comment by cewing** [comment]
@natea: I do not see any way to make this into a separate add-on package.  It's a change that is deeply embedded in core edx code.  It is possible that it might be accepted as a pull request but highly unlikely as the `course_module.id` used will often look something like this in the new split mongo store:

```
course-v1:org+course+run+branch@foobar+version_guid@14a7c9f3298ec
```

This change assumes the old `org/course/run` format, which is now deprecated.

**Comment by skleinfeldt** [comment]
From the doc:

> TJ says that there is a thread on edx-code about improvements to the way edX exports courses, so it could be that this fix will be unnecessary soon.

@natea have you tested Birch to find out how it handles this? If not can you do that? It would be ideal if we could avoid these kind of non-PR-acceptable core changes.

**Comment by natea** [comment]
@skleinfeldt I don't think Birch does course exports this way yet. I think TJ was saying that there's discussion about improving course exports on the edx-code mailing list, but that is most likely targeting a future version of edX (Cypress?)

@cewing correct, that commit has nothing to do with this feature. Not sure how it got in there (might have been me just forgetting to give that commit a heading in the gdoc)

**Comment by cewing** [comment]
The import code has changed significantly, but this aspect (calculating the export file's name) has not changed.  The current Birch code uses a deprecated API from a course module and the ISC updates use the course id but make assumptions about the structure of that id that are no longer valid since the advent of the split modulestore.

**Comment by cewing** [comment]
@natea: that commit is also under the heading of "Online labs", which seems a much better place for it.

**Comment by bryanlandia** [comment]
@cewing @natea - The target function is actually the same as modified by tkeemon for the named-release/birch tag.  There is a new function create_export_tarball (called by export_handler) created on master since the official Birch release.  I have duplicated tkeemon's naming changes in the import_export.py file based on its status at named-release/birch. Issue still pending running tests successfully.

**Comment by bryanlandia** [comment]
Should be complete with
https://github.com/jazkarta/edx-platform-for-isc/commit/a64ebfe7a4c28c42569262c7540f42463b9382a3

**Comment by bryanlandia** [comment]
@natea - Complete. please review at yr convenience.

**Comment by natea** [comment]
@bryanlandia will do.

**Comment by bryanlandia** [comment]
Closed as deployed and working on staging.
