### ISSUE TITLE
ISC Customizations: Add organization to user profile

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#6]
Preserve the changes made in [this commit](https://github.com/jazkarta/edx-platform/commit/b8bb1da5286aee231f53215292e28ee4ff1d1780)

Be sure to fix the indentation errors in the original commit to `common/djangoapps/students/models`

**Comment by cewing** [comment]
@natea: This change seems pretty uncontroversial (especially in light of the `REGISTRATION_EXTRA_FIELDS` configuration setting).  I think it'd be possible to put this into a pull request.  It would be great if it ended up in edx core and there was no need to keep porting it from named release to named release.  

It should be coupled with creating a migration, I think, to simplify the process of upgrading from stock Birch.

**Comment by cewing** [comment]
We must create a migration if only to keep the migration state synchronized with application model state.

**Comment by natea** [comment]
Agreed. I don't think edX would oppose an org field. Although I spoke with @andy-armstrong  at the edX birthday party yesterday and described this simple use case of wanting to extend the user profile model with additional fields, and how it's currently necessary to fork edx-platform to do so. He agreed that it should be possible to do simple modifications like this in a less intrusive way.

**Comment by bryanlandia** [comment]
Should be complete with https://github.com/jazkarta/edx-platform-for-isc/commit/fc3848689e342ecb72302dd2573aef165e76f370

**Comment by bryanlandia** [comment]
@natea -please review once I get you instructions to set up your environment

**Comment by natea** [comment]
@bryanlandia will do.

**Comment by bryanlandia** [comment]
confirmed working in the isc_appsember dev site

**Comment by bryanlandia** [comment]
Closing as deployed and tested on staging.
